### ISSUE TITLE
how can I configure my Sketchybar with your settings? thxs!

### ISSUE THREAD

**Issue by miremek** [FallenMax/sketchybar-config#2]
I have the Sketchybar configuration in /.config/sketchybar/sketchybarc (you know). But I don't know where I should put your files, do they all go in the .config folder?

A greeting and thanks in advance!

**Comment by FallenMax** [comment]
Hi miremek I'm not using Sketchybar now but I'm happy to help. 

This setup is a little bit complex and lacks documentation. It would be easier to tweak if you are comfortable to work on some javascript code and familiar to `yabai`.

There are several parts:

- Download (or build it yourself) [update_sketchybar.mjs](https://github.com/FallenMax/sketchybar-config/releases/download/0.0.1/update_sketchybar.mjs) - The main config file, it updates Sketchybar to reflects window/space state 
- Install [yabai](https://github.com/koekeishiya/yabai/tree/master) and use `.yabairc` provided in this repo - it's a tiling window manager, we configure it to run `update_sketchybar.mjs` whenever windows change
  - You need to modify .yabairc to point to your user directory
  - Also install [flock](https://github.com/discoteq/flock) as process lock
- Install node.js and zx globally - Required to run  `update_sketchybar.mjs`

**Comment by miremek** [comment]
> Hola miremek, no estoy usando Sketchybar ahora, pero estoy encantado de ayudar.
> 
> Esta configuración es un poco compleja y carece de documentación. Sería más fácil de ajustar si te sientes cómodo trabajando en algún código javascript y familiar para `yabai`.
> 
> Hay varias partes:
> 
> * Descarga (o constrúyelo tú mismo) [update_sketchybar.mjs ](https://github.com/FallenMax/sketchybar-config/releases/download/0.0.1/update_sketchybar.mjs)- El archivo de configuración principal, actualiza Sketchybar para reflejar el estado de la ventana/espacio
> * Install [yabai](https://github.com/koekeishiya/yabai/tree/master) and use `.yabairc` provided in this repo - it's a tiling window manager, we configure it to run `update_sketchybar.mjs` whenever windows change
>   
>   * Necesitas modificar .yabairc para apuntar a tu directorio de usuario
>   * También instale [flock ](https://github.com/discoteq/flock)como bloqueo de proceso
> * Instalar node.js y zx globalmente - Necesario para ejecutar`update_sketchybar.mjs`

Hi and thanks! I've realized that I don't really need sketchybar! It was just a whim that won't help me. Also, I don't know much about programming, so I'm still learning and getting into setting this up first will be a bit confusing (although I'll get there little by little). Thanks in advance! I would like macOS to be a little more customizable, I see your configuration as quite useful, actually, one of the most useful of the entire list of sketchybar configurations, which often only look for the aesthetic but little for the useful

**Comment by FallenMax** [comment]
>  I would like macOS to be a little more customizable ... which often only look for the aesthetic but little for the useful
 
Exactly what I thought! Thank you for the kind words! In case you ever want to play around Sketchybar (and this config) again, feel free to re-open this issue and ask anything!
